### ISSUE TITLE
 Could not dispatch event:class xxx to subscribing class

### ISSUE THREAD

**Issue by about-bob** [greenrobot/EventBus#303]
Hi,
It is work at Android Studio 1.5.1. 
There is an exception after i upgrade Android Studio from 1.5.1 to 2.1 RC.

`04-25 01:01:31.889 11907-12099/com.hello.pk E/NetService: INTIME onSocketInEvent start:p
04-25 01:01:31.899 11907-12099/com.hello.pk E/EventBus: Could not dispatch event: class com.xn.events.SocketInEvent to subscribing class class com.xn.network.service.NetService
                                                                java.lang.NoClassDefFoundError: Failed resolution of: Lcom/xn/network/frame/_base/FrameType;
                                                                    at com.xn.network.service.NetService.handleInEvent(NetService.java:221)
                                                                    at com.xn.network.service.NetService.onSocketInEvent(NetService.java:197)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
                                                                    at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:831)
                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xn.network.frame._base.FrameType" on path: DexPathList[[dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-uiframework2_9f440cc8d52b820e1d3627b19ed391861842741d-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-osbcp-css-parser-1.4_5af6b8309021587f87272734a2a426e7292738a8-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-intermediates-exploded-aar-androidasync-2.1.7_848a6ef6a1bcec9ba7ecb768eead4d4cdf22060d-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-httpclient-4.3.6_9c1e6a7210c449dba2530eac8d2039e86ace3906-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-htmlcleaner-2.2_48f4c6b9429151e866a777507ce5e22b52c8fd85-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-greendao-2.1.0_999e0a871d51e3c1c384e439431e8f36c4363085-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-eventbus-3.0.0_5c6af4cbf3d6b70a142e72d52a37de97c8ff4f8d-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-com.android.support-multidex-1.0.1_78441430e18306a893515f08efd587a194f57abc-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-android-support-v4_6f76359f419f4865282535849c61f43606bd40b1-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-android-async-http-1.4.9_075a2644403d8dfdc147c6daa35600e7ad0cc011-classes.dex", dex file "/data/data/com.hello.pk/files/instant-run/dex/slice-activeandroid-3.1-beta_f76d26225464eeef113b4537cd66cb5217730da7-classes.dex"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64, /vendor/lib64, /system/lib64]]
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                    at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                    at com.xn.network.service.NetService.handleInEvent(NetService.java:221) 
                                                                    at com.xn.network.service.NetService.onSocketInEvent(NetService.java:197) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485) 
                                                                    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479) 
                                                                    at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46) 
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                    at java.lang.Thread.run(Thread.java:831) 
                                                                	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.xn `

**Comment by greenrobot-team** [comment]
Have a look at the [FAQ](http://greenrobot.org/eventbus/documentation/faq/). Let me know if there is no solution for your issue there.
-ut
