### ISSUE TITLE
Fatal crash when registering androidx.appcompat.widget.AppCompatEditText with EventBus 

### ISSUE THREAD

**Issue by mourjan** [greenrobot/EventBus#608]
Android API 17
Emulator

My code
-----------------------------------------------------------------------------------------------
```java
import android.content.Context;
import android.util.AttributeSet;
import android.view.KeyEvent;

import androidx.appcompat.widget.AppCompatEditText;

import com.mourjan.classifieds.event.BackPressEditText;
import com.mourjan.classifieds.event.SoftKeyboard;

import org.greenrobot.eventbus.EventBus;
import org.greenrobot.eventbus.Subscribe;
import org.greenrobot.eventbus.ThreadMode;

public class SearchEditText extends AppCompatEditText {
    private boolean isSoftKeyboardShowing = false;

    public SearchEditText(Context context) {
        super(context);
    }

    public SearchEditText(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public SearchEditText(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    public boolean onKeyPreIme( int key_code, KeyEvent event )
    {
        if ( event != null && event.getKeyCode() == KeyEvent.KEYCODE_BACK && event.getAction() == KeyEvent.ACTION_UP ) {
            if (isSoftKeyboardShowing) {
                return false;
            }else {
                EventBus.getDefault().post(new BackPressEditText());
                return true;
            }
        }
        return super.onKeyPreIme( key_code, event );
    }

    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
/*error happens here */
        if(!EventBus.getDefault().isRegistered(this))EventBus.getDefault().register(this);
    }

    @Override
    protected void onDetachedFromWindow() {
        if(EventBus.getDefault().isRegistered(this))EventBus.getDefault().unregister(this);
        super.onDetachedFromWindow();
    }

    @Subscribe(threadMode = ThreadMode.MAIN)
    public void onMessageEvent(SoftKeyboard event) {
        isSoftKeyboardShowing = event.isShowing();
    }
}
```

------------------------------------------------------------------------------------------------
Error Stacktrace
------------------------------------------------------------------------------------------------

```java
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: android/view/textclassifier/TextClassifier
        at java.lang.Class.getDeclaredMethods(Native Method)
        at java.lang.Class.getPublicMethodsRecursive(Class.java:955)
        at java.lang.Class.getMethods(Class.java:938)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
        at com.mourjan.classifieds.component.SearchEditText.onAttachedToWindow(SearchEditText.java:48)
        at android.view.View.dispatchAttachedToWindow(View.java:11937)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1192)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
        at android.view.Choreographer.doFrame(Choreographer.java:532)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.textclassifier.TextClassifier" on path: /data/app/com.mourjan.classifieds-1.apk
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at java.lang.Class.getDeclaredMethods(Native Method) 
        at java.lang.Class.getPublicMethodsRecursive(Class.java:955) 
        at java.lang.Class.getMethods(Class.java:938) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64) 
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:140) 
        at com.mourjan.classifieds.component.SearchEditText.onAttachedToWindow(SearchEditText.java:48) 
        at android.view.View.dispatchAttachedToWindow(View.java:11937) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2422) 
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1192) 
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989) 
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:562) 
        at android.view.Choreographer.doFrame(Choreographer.java:532) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735) 
        at android.os.Handler.handleCallback(Handler.java:725) 
        at android.os.Handler.dispatchMessage(Handler.java:92) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by greenrobot-team** [comment]
Apparently you are using [`TextClassifier`](https://developer.android.com/reference/android/view/textclassifier/TextClassifier.html) in your code which requires API level 26.

See the FAQ about `NoClassDefFoundError` for more details.
http://greenrobot.org/eventbus/documentation/faq/

**Comment by mourjan** [comment]
I am not using TextClassifier in my code and my app's minSdkVersion is 17. and as you can see within the snippet of my code, I am just extending androidx.appcompat.widget.AppCompatEditText and EventBus is crashing when trying to register this component to its events when running on Android Emulator with API version 17.

**Comment by zongxiaomi** [comment]
> After digging around, this problem occurs after upgrading androidx.appcompat:appcompat from 1.0.2 to the latest 1.1.0

why?

**Comment by mourjan** [comment]
> why?

I have no idea, and I ended up going with another solution that was not based on EventBus

**Comment by inteist** [comment]
I have the same issue - the reason seems to be the same – androidx library update to 1.1.0 (in my case from 1.0.0) 

and I can't even downgrade because it is a cascading dependency 

I suppose if this is not (very) promptly fixed, I will have to look for another solution for event bus as well :(

**Comment by greenrobot-team** [comment]
I suppose this could be fixed by EventBus ignoring the `androidx` package (like the suggested fix at https://github.com/greenrobot/EventBus/pull/610/files#diff-385c3ea511f8ed68ec0b4243fdf5ce62).

**Comment by greenrobot-team** [comment]
Fixed with 62abc54dec3bf3e1f8d2badc4752f61ff05e8eb3. Will be available in the next release.
